{
 "title": "Playground",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Is Syncing",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "substrate",
     "query": "SELECT \"isSyncing\" AS \"isSyncing\" FROM \"substrate\"",
     "select": [
      [
       { "params": [ "isSyncing" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Highest block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "substrate",
     "query": "SELECT last(\"highestBlock\") AS \"highestBlock\" FROM \"substrate\"",
     "select": [
      [
       { "params": [ "currentBlock" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "substrate",
     "query": "SELECT last(\"currentBlock\") AS \"currentBlock\" FROM \"substrate\"",
     "select": [
      [
       { "params": [ "currentBlock" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}